### PR TITLE
VLC and Wesnoth

### PR DESCRIPTION
**Pull request by mbattista**
- Added VLC as a player for local video files
- Added wesnoth as some kind of showcase that even games could be played / watched together
- Added enviroment variables in the README file

### CODE REVIEW

**Comment by m1k1o** [comment]
Hey, thanks for contibution. Documentation looks fine.

I would rather stick to the general usecases for everyone. There is many softwares that can neko support, in fact, any. VLC is a good addition for watching films, but I think Wesnoth is already too specific. If someone wants to have it, they can install it on their own.

Maybe there would be another idea to split there specific usecases to some kind of `neko-awesome` list, what would be meant exactly for this - adding all variety of software to neko, not just browser. Wdys?

**Comment by mbattista** [comment]
I am with you, that Wesnoth kind of specific.

I would have preferred a Steam container, which then opens a lot of possibilities. But also a lot of games, which will not run.
My idea behind Wesnoth was not the game (which I never have played) but more of a showcase what else could be possible with this project.

**Comment by m1k1o** [comment]
On the orher hand, providing some user interface where anyone can install what they want could be also good idea. 

There exists some attempts in upstream repository: https://github.com/nurdism/neko/blob/master/.docker/files/xfce4/Dockerfile

Maybe adding `xfce4` etc. would be the general accepted solution.

**Comment by mbattista** [comment]
Removed Wesnoth added xfce

added sudoers for installation purposes.
Standard sudo password is neko. Thought about setting the password via docker env, but then there would be one parameter which has only effect in one container.

**Comment by m1k1o** [comment]
Or just allow that user to execute sudo without password, and none is needed. But that is another security concern. I think, in container could be allowed.

**Comment by mbattista** [comment]
Now sudo without password.

It throws sometimes GTK warnings, but nothing critical and I could install and run different applications.

**Comment by m1k1o** [comment]
I changed VLC not to prompt at first run, to be fullscreen (apparently openbox identifiers are case sensitive) and then added ability to automatically add folder to playlist.

**Pull request merged**
