### PR TITLE
Arm container

### PR DESCRIPTION
**Pull request by mbattista**
Added new container for ARMv7 / ARMv8 raspberry pis

### CODE REVIEW

**Comment by mbattista** [comment]
You can test the container with `mbattista/neko;arm_firefox`

**Comment by m1k1o** [comment]
Is audio working for you?

**Comment by mbattista** [comment]
I have sound.

More importantly I noticed that the missing SPS information which are added by `h264parse config-interval=x` are the reason the `v4l2h264enc` pipeline did not run.

With `config-interval` the a pipeline with `v4l2h264enc` is less CPU demanding.
Only problem now, is that now the colorspace is shifted. E.g. The YouTube Symbol is blue, the Firefox active tab is orange and so on...

**Comment by m1k1o** [comment]
In my previous setup, I had no sound but when I tried it again, I have. Weird. Can be host browser issues.

Did you try modifying `colorimetry` to correct colorspace?

```
video/x-raw,framerate=30/1,format=NV12,colorimetry=bt709
```

**Comment by mbattista** [comment]
Pipeline:
```
      NEKO_VIDEO: ' ximagesrc display-name=%s use-damage=0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue ! v4l2h264enc extra-controls="controls,h264_profile=0,video_bitrate=1250000;" ! h264parse config-interval=3 ! video/x-h264,profile=baseline,stream-format=byte-stream '
```

colorimetry leads to no video in my case.

**Comment by mbattista** [comment]
Ok. Now I think that I found the reason.

I pushed the updated README in the pipeline.

Can you test it with the following docker-compose:
```
version: "3.4"
services:
  neko:
    image: "mbattista/neko:arm_firefox"
    restart: "unless-stopped"
    shm_size: "540mb"
    ports:
      - "8084:8080"
      - "52000-52100:52000-52100/udp"
    privileged: true
    environment:
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: 'neko'
      NEKO_PASSWORD_ADMIN: 'admin'
      NEKO_EPR: 52000-52100
      NEKO_VP8: 'false'
      NEKO_VP9: 'false'
      NEKO_H264: 'true'
      NEKO_VIDEO_BITRATE: 3500
      NEKO_VIDEO: ' ximagesrc display-name=%s use-damage=0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue ! video/x-raw,framerate=30/1,format=NV12 ! v4l2h264enc extra-controls="controls,h264_profile=0,video_bitrate=1250000;" ! h264parse config-interval=3 ! video/x-h264,profile=baseline,stream-format=byte-stream '
      NEKO_MAX_FPS: 0
      NEKO_OPUS: 'true'
```

**Comment by m1k1o** [comment]
Yes, it is working with new pipeline. I am even able to watch YouTube. Although, it is super-slow while navigating, watching video is surprisingly smooth!

**Comment by m1k1o** [comment]
Weird enough, sound is not working again, for me. It is interesing why it is sometimes working and sometimes not.

**Comment by mbattista** [comment]
Do you have any output of the Docker?

I noticed that under load pulseaudio sometimes ceashes and cannot strartet / closed.

I can look if I can configure supervisord to close and restart pulseaudio in that szenario.

**Comment by m1k1o** [comment]
Oh yeah, that is a good idea. It can be that. After I restarted it, it works again, yo don't have any output yet.

**Comment by mbattista** [comment]
Could it be a Codec Problem?

`https://www.youtube.com/watch?v=Dxm3cHrKcbA` => no sound
`https://www.youtube.com/watch?v=c5wkyF7PaZM` => sound

It seems music in general did not work for me, but speech seemed to work.

**Comment by m1k1o** [comment]
Codecs seems to be the same:

Not working:
image

Working:
image


We already have Chromium in our build, so we should go with that.

**Comment by mbattista** [comment]
Since the Chromium in the build does not have any ARM builds in the repo, I will take the the upstream Chromium via `sudo apt-get install chromium-browser`

**Comment by m1k1o** [comment]
Thats fine, i think it should be separated in the furute, to have vanilla chromium & chromium ungoogled.

**Comment by mbattista** [comment]
```
version: "3.4"
services:
  neko:
    image: "mbattista/neko:chromium_arm"
    restart: "unless-stopped"
    shm_size: "540mb"
    ports:
      - "8084:8080"
      - "52000-52100:52000-52100/udp"
    privileged: true
    environment:
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: 'neko'
      NEKO_PASSWORD_ADMIN: 'admin'
      NEKO_EPR: 52000-52100
      NEKO_VP8: 'false'
      NEKO_VP9: 'false'
      NEKO_H264: 'true'
      NEKO_VIDEO_BITRATE: 3500
      NEKO_VIDEO: ' ximagesrc display-name=%s use-damage=0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue ! video/x-raw,framerate=30/1,format=NV12 ! v4l2h264enc extra-controls="controls,h264_profile=0,video_bitrate=1250000;" ! h264parse config-interval=3 ! video/x-h264,profile=baseline,stream-format=byte-stream '
      NEKO_MAX_FPS: 0
      NEKO_OPUS: 'true'
```

sound seems now to work.
there are some other errors in the branch now, but can you test it, if it works on your pi?

**Comment by m1k1o** [comment]
There are just small issues with openbox and window placement, but apart from that I ges sound on videos where I did not get previously.

image

Also the playing is smooth, I am able to watch video without major interruptions. Sometimes I get "Page unresponsive" dialog, and video is loading, but that's expected.

**Comment by m1k1o** [comment]
Although the quality sometimes drops drastically. But that looks like raspberry pi running out of resources.

image

**Comment by m1k1o** [comment]
I moved things around a bit, and added generic build gor `arm-` images, if we ever want to have different. And also replaced ungoogled chomium with vanilla to support ARM. Not sure about the package, if is the same `chromium` vs. `chromium-browser`. Need to test it on my Pi first.

**Comment by m1k1o** [comment]
Tested, it works alright.

**Comment by GigaFyde** [comment]
@mbattista here's some pi4 optimized images

`gigafyde/neko:pi4-base`
`gigafyde/neko:pi4-firefox`

**Pull request merged**
