### PR TITLE
Install latest Ungoogled Chromium extensions at build time

### PR DESCRIPTION
**Pull request by whalehub**
I should have done this a long time ago, but I never got around to implementing this idea until now.

### CODE REVIEW

**Comment by m1k1o** [comment]
Looks good, i would make it as loop because there is lots of dupliacted code. So that you can specify list of ids of extensions that will be installed.

**Comment by whalehub** [comment]
@m1k1o Good idea! Just finished rewriting my pull request.

**Comment by whalehub** [comment]
@m1k1o FYI, the default Dockerfile shell is `/bin/sh`, which doesn't support arrays. That's why I changed it to `/bin/bash` using the [SHELL](https://docs.docker.com/engine/reference/builder/#shell) instruction.

**Comment by m1k1o** [comment]
I am trying it right now, `mkdir -p ${EXTENSIONS_DIR};` seems to be missing. And even after adding that I don'ŧ see extensions in the browser. I am gonna try again...

**Comment by m1k1o** [comment]
@whalehub there is missing `,` in extensions json, i guess thats why it fails to load.

**Comment by whalehub** [comment]
@m1k1o Nice catch, I can confirm that it's working now. The pull request should be good to merge.

**Pull request merged**
