### PR TITLE
even larger buffer

### PR DESCRIPTION
**Pull request by mbattista**
https://github.com/m1k1o/neko/commit/14939db65a56024c19a27a76ec6d69e4a2502364

reintroduced lags for me.
Perhaps the buffer should even bigger then in this PR?

### CODE REVIEW

**Comment by m1k1o** [comment]
Interesting! Didn't know that. Let me then add it to ENV so we can configure it for us.

**Comment by m1k1o** [comment]
I reverted changes 19631d8ae986a0c6172e5670ab09fcefc340dea0 and will think about workaround. Maybe setting using ENV. Shoudl fix issue for you now.

**Comment by mbattista** [comment]
I think increasing the encoder buffer is will (hopefully) not have any negative impact on the gstreamer pipeline.

I will test with some big numbers and will tell you the results.

**Comment by m1k1o** [comment]
My only concern about having large `max keyframes dist` is long initial loading time. But that could be solved by adding some spinner on client, what shows "loading" or any user feedback, so that it does not look like it is broken. When it better performs the whole session, then it should be prefered even if it increases initial startup time.

**Comment by mbattista** [comment]
made some improvements to the h264 quality.

only problem is, that now the first person needs to change the resolution one time so start the video.
could be related to https://github.com/pion/webrtc/issues/1625 or just an other error in the pipeline that i am not seeing yet.

**Comment by m1k1o** [comment]
I faced similar issue, when I tried Nvidia's transcoding `nvenc`. I just needed to switch between qualities to get some video.

**Comment by mbattista** [comment]
I noticed that the Pipeline I will write will only be tested on an old i7 2600k and will therefore always be an lower limit of the quality.

I am thinking about making every gstreamer parameter an available setting for the docker file, so IF you have better hardware you can configure the pipeline to find your sweet spot (even with nvenc / Quick Sync).

I will also run some tests in a cloud to check some parameter against vCPUs.

At last I would like to add some more container to showcase the possibilities of the project. I am thinking about freeCIV, flare or/and hedgewars.

**Comment by m1k1o** [comment]
That is not really necessary, since you can specify whole pipeline as a parameter `NEKO_VIDEO`. If you really want to customize it. Default values should match most common usecases, and with your latest chages, outside of this PR, I see it is working really good.

**Comment by mbattista** [comment]
`NEKO_VIDEO` is not well documented.

I could add some examples to the `docker-compose.yml`.
H264 hardware encoding is very common in modern CPUs/GPUs which could help to improv the quality even further. (E.g. tune=zerolatency could be dropped)

**Comment by m1k1o** [comment]
Is not documented, I agree. Examples would help much. But most of the user want to only plug'n'play, so they don't bother with any settings.

I could get H264 hardware encoding working with Nvidia, but I didn't saw much difference, I neeed to completly rebuild container with nvidia support, which was not really easy thing to do. Another GPUs I don't have, so I didn't try. 

Maybe leveraging VAAPI would be interesing, but I'm missing proper hardware to test it.

**Pull request closed without merging**
