### PR TITLE
add generic ArrayIn function with minimal type casting

### PR DESCRIPTION
**Pull request by eos175**

### CODE REVIEW

**Comment by m1k1o** [comment]
Looks good. But probably array could be []T and not any to make things even easier.

**Comment by eos175** [comment]
You would need to cast beforehand, which I think is fine. Let me know if I should do it.

image

**Comment by m1k1o** [comment]
Yeah, it would be better to change types it all the way down, because its just string and it prevents unnecessary panic.

**Comment by eos175** [comment]
There can't be a panic because the cast is safe. However, `exclude` is always `[]string`, so it's better to change it

**Pull request merged**
