### PR TITLE
Added Vivaldi Image

### PR DESCRIPTION
**Pull request by Xeddius**
Vivaldi browser for n.eko.
It's currently using a dummy "default" profile.
I'm working on contacting a developer to see if we can get some kind of preferences.json support and possibly a link to latest builds for ease of integration/updates.

The .json files are vestigial and hopefully they will be of use in future vivaldi releases.

### CODE REVIEW

**Comment by m1k1o** [comment]
How will be the update procedure of extensions? Is vivaldi loading them automatically or are they stored in the profile? I also see there are some leftovers from your profile, maybe we should generate new one. Or is it needed?

image

For openbox class needs to have capitalized first letter `Vivaldi-stable*"` but decoration does not seem to disappear. We would need vivaldi to force using system decorations.
```
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "Vivaldi - Vivaldi"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = 
_OB_APP_CLASS(UTF8_STRING) = "Vivaldi-stable"
_OB_APP_NAME(UTF8_STRING) = "vivaldi-stable (/home/neko/.config/vivaldi)"
_OB_APP_ROLE(UTF8_STRING) = "browser"
```

**Comment by m1k1o** [comment]
When leaving out whole profile setup, looks like it did picl up the preferences file. Changing avatar index to `"avatar_index": 34,`, because that is a cat, I see correct name of the user:

image

**Comment by Technetium1** [comment]
@Xeddius Why Vivaldi?

**Comment by Xeddius** [comment]
@m1k1o Incredible, Thank you! I think with your changes it'll be a good addition, and I did forget to clear the deletion history from bookmarks, I was using the default profile folder for extensions as I wasn't sure how to enable them without the preferences.json working, but it seems you've managed to get most of this fixed fairly quick.

**Comment by m1k1o** [comment]
We could install extensions the same way as here: https://github.com/m1k1o/neko/pull/183

**Comment by m1k1o** [comment]
Moved to https://github.com/m1k1o/neko/pull/186

**Pull request closed without merging**
