### PR TITLE
missing NEKO_BIND

### PR DESCRIPTION
**Pull request by gbrian**
Just adding a missing conf setting

### CODE REVIEW

**Comment by m1k1o** [comment]
There might be missing more. Would be worth looking into it.

**Comment by gbrian** [comment]
I'll take a look

**Comment by jemand771** [comment]
just mentioning `NEKO_TCPMUX` and `NEKO_UDPMUX` here for completeness. they're experimental, but they exist

added in #106, example usage: https://github.com/m1k1o/neko/issues/118#issuecomment-997810434

**Comment by gbrian** [comment]
@m1k1o can we merge this?

**Comment by m1k1o** [comment]
Added all missing env vars in af9289866dc2a44a539185f99c196a3e4e4d04dc.

**Pull request closed without merging**
