### PR TITLE
Add nvidia docker gpu acceleration

### PR DESCRIPTION
**Pull request by m1k1o**
Inspired by [qwantify fork](https://github.com/wanjohiryan/qwantify) that succesfully implemented [docker-nvidia-egl-desktop](https://github.com/ehfd/docker-nvidia-egl-desktop).

Issue #228.
Issue #226.
Issue #213.

TODO: Add `nvenc` to gstreamer, help wanted.

### CODE REVIEW

**Comment by m1k1o** [comment]
Google chrome is currently unable to use GPU using EGL. We need to wait until VirtualGL reaches stable on its 3.1 branch.
https://github.com/selkies-project/docker-nvidia-egl-desktop/issues/20

**Comment by m1k1o** [comment]
Gstreamer with nvcodec: https://gist.github.com/m1k1o/28c73fc15cd1fba59b73364c3b7a5d0a

**Comment by Uruknara** [comment]
@m1k1o are you gonna make it compatible soon ?

**Comment by yesBad** [comment]
> @m1k1o are you gonna make it compatible soon ?

It's done when it's done. 🍿

**Comment by Uruknara** [comment]
Yes i understand no problem

**Comment by Uruknara** [comment]
Virtual GL got 3.1 stable now !

**Comment by m1k1o** [comment]
Nice! Thanks for letting me know @Uruknara gonna try it out.

**Comment by Uruknara** [comment]
What are you waiting for to merge this ?

Need beta tester ?

**Comment by m1k1o** [comment]
I tried it out, but does not seem to work :( Added details here:
https://github.com/selkies-project/docker-nvidia-egl-desktop/issues/20

**Comment by yesBad** [comment]
> I tried it out, but does not seem to work :( Added details here: [selkies-project/docker-nvidia-egl-desktop#20](https://github.com/selkies-project/docker-nvidia-egl-desktop/issues/20)

Seems like they solved it for ya, excellent :D

**Comment by m1k1o** [comment]
Yes. They did! Preparing to merge this now. Doing some last tests.

**Pull request merged**
