### PR TITLE
Emoji support

### PR DESCRIPTION
**Pull request by yesBad**
Fixes emojis by adding Google's Noto Emoji.

### CODE REVIEW

**Comment by yesBad** [comment]
chrome_DLGxndPDfC
chrome_aTvPtZ2WFY

**Comment by m1k1o** [comment]
Looks like 99.99% OK, interesting why just one is missing. 
image

But I guess we can safely ignore that one.

**Comment by yesBad** [comment]
Yeah not sure what that one is... But yeah pretty much everything seems to work.
At least it's better than nothing.

**Comment by yesBad** [comment]
chrome_X0snfKXr9K
Doesn't even work on Windows 10... Yeah I think its fine to ignore.

**Pull request merged**
