### PR TITLE
Fix connect

### PR DESCRIPTION
**Pull request by wselfjes**

### CODE REVIEW

**Comment by Technetium1** [comment]
Should definitely ban AI PRs. What a dystopian future we're witnessing...

**Comment by m1k1o** [comment]
Not sure if this is from AI or just the company that is trying to use neko has the word AI in it. If that's how it is, they should really consider sponsoring.

**Comment by Technetium1** [comment]
@m1k1o seems to be a combination
https://github.com/CoTester-ai/coTester/commit/78184e1456e750a5eb54fe1f5f27d8c08fb7a9e0
https://github.com/CoTester-ai/coTester/pull/96

@vbakhteev & @wselfjes please explain; are you launching a product with Neko?

**Comment by wselfjes** [comment]
Yes, we found neko very suitable for us.
We are now at [cotester.ai](https://cotester.ai/) completing the transition from hyperbeam to a standalone neko-based solution.

**Comment by m1k1o** [comment]
> Yes, we found neko very suitable for us.
We are now at [cotester.ai](https://cotester.ai/) completing the transition
from hyperbeam to a standalone neko-based solution.

Sounds interesting, @wselfjes, thanks for sharing. So you were able to
minimize cost of the service hyperbeam using neko.

**Pull request closed without merging**
